apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: bluegreen-subs
  namespace: bluegreen
  labels:
    app: bluegreen
  annotations:
    apps.open-cluster-management.io/github-path: resources/bluegreen
spec:
  channel: bluegreen/bluegreen-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-clusters